import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { openStore } from '../server/store.js';
import { Supervisor } from '../server/supervisor.js';
test('chat, drafts and old-schema data survive additive Gmail migration and reopen',()=>{const directory=mkdtempSync(join(tmpdir(),'migration-')),path=join(directory,'fixture.sqlite');let db=openStore(path);try{db.prepare('INSERT INTO leads(id,name,email,company,city,notes,source) VALUES(?,?,?,?,?,?,?)').run('lead','Ayesha','ayesha@example.com','Studio','Karachi','note','import.csv');db.prepare('INSERT INTO chat VALUES(?,?,?,?)').run('message','user','Karachi ke leads ke liye draft banao','now');db.prepare('INSERT INTO drafts VALUES(?,?,?,?,?,?,?)').run('draft','task','lead','Hello','Personalized draft','demo','now');db.exec('DROP TABLE mail_actions; DROP TABLE campaigns;');db.close();db=openStore(path);assert.equal((db.prepare('SELECT text FROM chat').get() as any).text,'Karachi ke leads ke liye draft banao');assert.equal((db.prepare('SELECT body FROM drafts').get() as any).body,'Personalized draft');assert.equal((db.prepare('SELECT source FROM leads').get() as any).source,'import.csv');assert.ok(db.prepare('PRAGMA table_info(campaigns)').all().some((c:any)=>c.name==='sender'));}finally{db.close();rmSync(directory,{recursive:true,force:true});}});
test('unreviewed planning task cannot start, and cancellation survives recovery',()=>{const db=openStore(':memory:');try{db.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?)').run('plan','request','drafts','demo','needs_user','Planning your request',null,'now');const supervisor=new Supervisor(db);assert.equal((db.prepare('SELECT state FROM tasks').get() as any).state,'failed');assert.throws(()=>supervisor.control('plan','start'),/reviewed/);supervisor.control('plan','cancel');new Supervisor(db);assert.equal((db.prepare('SELECT state FROM tasks').get() as any).state,'cancelled');}finally{db.close();}});
