import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { openStore } from '../server/store.js';
import { Supervisor } from '../server/supervisor.js';
import { GuidedSetup,SAMPLE_INSTRUCTION } from '../server/setup.js';
import { Gmail,TokenVault } from '../server/gmail.js';
import { Campaigns } from '../server/campaigns.js';
import { selectLeads } from '../server/selection.js';
import { plan,health } from '../server/provider.js';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'guided-test-'));const db=openStore(join(dir,'fixture.sqlite'));const supervisor=new Supervisor(db),gmail=new Gmail(new TokenVault(join(dir,'tokens'))),setup=new GuidedSetup(db,gmail,supervisor);return {db,supervisor,gmail,setup,dir,close(){db.close();rmSync(dir,{recursive:true,force:true});}};}
test('configuration presence never verifies setup, receipts invalidate on key changes and are not exposed',()=>{const saved={...process.env};const f=fixture();try{process.env.PORT='3000';process.env.GOOGLE_REDIRECT_URI='';process.env.GEMINI_API_KEY='private-fixture';process.env.FREE_TIER_CONFIRMED='true';process.env.AI_DATA_CONSENT='true';process.env.GOOGLE_CLIENT_ID='fixture-client';process.env.GOOGLE_CLIENT_SECRET='fixture-secret';health.code='not_checked';let data=f.setup.summary('http://localhost:3000');assert.equal(data.steps[0].status,'Configured but unverified');assert.equal(data.steps[1].status,'Configured but unverified');assert.equal(data.callback.registrationVerified,false);f.setup.record('ai','verified','Mocked test evidence',f.setup.aiContext());data=f.setup.summary('http://localhost:3000');assert.equal(data.steps[0].status,'Verified');assert.ok(!JSON.stringify(data).includes('private-fixture'));assert.ok(!JSON.stringify(data).includes('fixture-secret'));assert.ok(!JSON.stringify(data).includes('context'));process.env.GEMINI_API_KEY='changed-fixture';assert.equal(f.setup.summary('http://localhost:3000').steps[0].status,'Configured but unverified');process.env.GOOGLE_REDIRECT_URI='http://localhost:9999/api/gmail/callback';assert.equal(f.setup.summary('http://localhost:3000').steps[1].status,'Needs attention');assert.throws(()=>f.gmail.callback(),/exactly match/);}finally{for(const key of ['PORT','GOOGLE_REDIRECT_URI','GEMINI_API_KEY','FREE_TIER_CONFIRMED','AI_DATA_CONSENT','GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET']){if(saved[key]===undefined)delete process.env[key];else process.env[key]=saved[key];}f.close();}});
test('UAE hardware country aliases and industry filters exclude non-targets',async()=>{const p=await plan(SAMPLE_INSTRUCTION,'demo');assert.equal(p.country,'UAE');assert.equal(p.industry,'hardware');const selected=selectLeads([{name:'a',country:'UAE',industry:'hardware'},{name:'b',country:'United Arab Emirates',industry:'hardware stores'},{name:'c',country:'Pakistan',industry:'hardware'},{name:'d',country:'UAE',industry:'software'}],p);assert.deepEqual(selected.map(l=>l.name),['a','b']);});
test('guided demo imports bounded samples, persists exactly selected drafts, survives reopen and does not verify live',async()=>{const f=fixture();const timer=setInterval(()=>void f.supervisor.tick(),10);try{const id=randomUUID();const result=await f.setup.verifyWorkflow('demo',id);assert.equal(result.drafts,2);assert.equal(f.db.prepare('SELECT count(*) n FROM leads').get()!.n,4);assert.equal(f.db.prepare('SELECT count(*) n FROM drafts').get()!.n,2);assert.equal(f.db.prepare('SELECT count(*) n FROM mail_actions').get()!.n,0);const dupe=await f.setup.verifyWorkflow('demo',id);assert.equal(dupe.duplicate,true);assert.equal(f.db.prepare('SELECT count(*) n FROM drafts').get()!.n,2);const receipt=f.setup.summary('http://localhost:3000').steps[2];assert.equal(receipt.status,'Configured but unverified');assert.equal(receipt.mode,'demo');const reopened=openStore(join(f.dir,'fixture.sqlite'));try{assert.equal(reopened.prepare('SELECT count(*) n FROM drafts').get()!.n,2);assert.equal((reopened.prepare("SELECT mode FROM setup_checks WHERE name='workflow'").get() as any).mode,'demo');}finally{reopened.close();}const campaigns=new Campaigns(f.db,f.gmail);assert.throws(()=>campaigns.create({requestId:randomUUID(),title:'No samples',limit:1,draftIds:[(f.db.prepare('SELECT id FROM drafts LIMIT 1').get() as any).id]}),/Sample leads/);}finally{clearInterval(timer);f.close();}});
test('one durable optional test review and no implicit authorization',()=>{const f=fixture();try{const campaigns=new Campaigns(f.db,f.gmail);const requestId=randomUUID();const test={requestId,recipient:'qa@workbench.test',subject:'One email',body:'Review only'};const original=campaigns.createTest(test);assert.equal(campaigns.createTest(test).id,original.id);assert.throws(()=>campaigns.createTest({...test,requestId:randomUUID(),body:'Another test'}),/single-test campaign/);assert.equal(f.setup.summary('http://localhost:3000').steps[3].status,'Configured but unverified');assert.equal((f.db.prepare('SELECT state FROM mail_actions').get() as any).state,'draft');}finally{f.close();}});
