import {test} from 'node:test';
import assert from 'node:assert/strict';
import {bounded503,retryDelay,TransientFailure} from '../server/transient.js';
import {openStore} from '../server/store.js';
import {Supervisor} from '../server/supervisor.js';
test('503 budgets honor headers, jitter, elapsed cap and cancellation',async()=>{
 assert.equal(retryDelay('10',1,0),10000);assert.equal(retryDelay(new Date(10000).toUTCString(),1,0),10000);assert.equal(retryDelay(null,2,0,()=>0),1000);
 let now=0,calls=0;const runtime={now:()=>now,random:()=>0,sleep:async(ms:number)=>{now+=ms;}};
 await assert.rejects(()=>bounded503(async()=>{calls++;return {unavailable:true};},{},runtime),TransientFailure);assert.equal(calls,3);assert.equal(now,1500);
 calls=0;now=0;await assert.rejects(()=>bounded503(async()=>{calls++;return {unavailable:true,retryAfter:'100'};},{},runtime),TransientFailure);assert.equal(calls,1);
 calls=0;now=0;await assert.rejects(()=>bounded503(async()=>{calls++;now+=60000;return {unavailable:true};},{},runtime),TransientFailure);assert.equal(calls,2);
 calls=0;now=0;await assert.rejects(()=>bounded503(async()=>{calls++;return {unavailable:true};},{active:()=>now<200},runtime),/stopped/);assert.equal(calls,1);
});
function fixture(){const db=openStore(':memory:');db.prepare('INSERT INTO leads(id,name,email,company,city,notes,source) VALUES(?,?,?,?,?,?,?)').run('lead','Sample','s@example.com','Sample Hardware','Dubai','','Guided setup sample (do not send)');db.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?)').run('task','request','Dubai ke 1 lead ka draft banao','live','paused','review',null,new Date().toISOString());return db;}
test('draft exhaustion pauses, resumes only pending steps and preserves unique drafts',async()=>{const db=fixture();db.prepare("INSERT INTO steps(task_id,lead_id,state) VALUES('task','lead','pending')").run();let fail=true;const sup=new Supervisor(db,async()=>{if(fail)throw new TransientFailure();return {subject:'Sample',body:'Sample draft'};});sup.control('task','start');await sup.tick();assert.equal(db.prepare('SELECT state FROM tasks').get()?.state,'paused');assert.equal(db.prepare('SELECT next_retry FROM tasks').get()?.next_retry,null);fail=false;sup.control('task','resume');await sup.tick();await sup.tick();assert.equal(db.prepare('SELECT state FROM tasks').get()?.state,'completed');assert.equal(db.prepare('SELECT count(*) n FROM drafts').get()?.n,1);await sup.tick();assert.equal(db.prepare('SELECT count(*) n FROM drafts').get()?.n,1);db.close();});
test('planning exhaustion has durable resume gate and never completes an empty task',async()=>{const db=fixture();db.prepare("INSERT INTO task_plans VALUES('task',NULL)").run();let fail=true;const sup=new Supervisor(db,undefined,async()=>{if(fail)throw new TransientFailure(Date.now()+10000);return {city:'Dubai',company:'',country:'',industry:'',limit:1,language:'roman-urdu',reply:'Sample selected'};});sup.control('task','start');await sup.tick();assert.equal(db.prepare('SELECT state FROM tasks').get()?.state,'paused');assert.throws(()=>sup.control('task','resume'),/Retry-After/);db.prepare('DELETE FROM task_retry_holds').run();fail=false;sup.control('task','resume');await sup.tick();assert.equal(db.prepare('SELECT state FROM tasks').get()?.state,'paused');assert.equal(db.prepare('SELECT count(*) n FROM steps').get()?.n,1);assert.equal(db.prepare('SELECT count(*) n FROM drafts').get()?.n,0);assert.equal(db.prepare('SELECT count(*) n FROM task_plans').get()?.n,0);db.close();});
