import { randomUUID,createHash } from 'node:crypto';
import { z } from 'zod';
import { event,type Store } from './store.js';
import { Gmail,MailError } from './gmail.js';
const email=z.string().email().max(254).transform(v=>v.toLowerCase());
const subject=z.string().trim().min(1).max(300).refine(v=>!/[\r\n]/.test(v),'Subject must be one line.');
const body=z.string().trim().min(1).max(5000);
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export class Campaigns {
 busy=false;
 constructor(public db:Store,public gmail:Gmail){db.prepare("UPDATE mail_actions SET state='uncertain',error='Server stopped during send. Reconcile in Gmail Sent; resend blocked.' WHERE state='sending'").run();db.prepare("UPDATE campaigns SET state='paused',reason='Server restarted. Review outcomes and resume.',next_retry=NULL WHERE state IN ('authorized','running')").run();}
 snapshot(){return {campaigns:this.db.prepare('SELECT * FROM campaigns ORDER BY created DESC').all(),mailActions:this.db.prepare('SELECT * FROM mail_actions ORDER BY rowid').all()};}
 create(input:unknown){const data=z.object({requestId:z.string().uuid(),title:z.string().trim().min(1).max(200),draftIds:z.array(z.string().uuid()).min(1).max(100),limit:z.number().int().min(1).max(100)}).parse(input);const prior=this.db.prepare('SELECT id FROM campaigns WHERE request_id=?').get(data.requestId);if(prior)return prior;
 if(new Set(data.draftIds).size!==data.draftIds.length||data.draftIds.length>data.limit)throw Error('Select distinct drafts within the sending limit.');
 const messages=data.draftIds.map(id=>{const d:any=this.db.prepare('SELECT d.*,l.email,l.name,l.source FROM drafts d JOIN leads l ON l.id=d.lead_id WHERE d.id=?').get(id);if(!d)throw Error('A selected draft no longer exists.');if(d.source==='Demo samples'||d.source==='Guided setup sample (do not send)')throw Error('Sample leads cannot receive real email.');return {draftId:d.id,recipient:email.parse(d.email),name:d.name,subject:subject.parse(d.subject),body:body.parse(d.body)};});
 if(new Set(messages.map(m=>m.recipient)).size!==messages.length)throw Error('A campaign can include each recipient only once.');return this.insert(data.requestId,data.title,data.limit,messages);
 }
 createTest(input:unknown){const data=z.object({requestId:z.string().uuid(),recipient:email,subject,body}).parse(input);const prior=this.db.prepare('SELECT id FROM campaigns WHERE request_id=?').get(data.requestId);if(prior)return prior;if(this.db.prepare("SELECT id FROM campaigns WHERE title='Single test email' LIMIT 1").get())throw Error('A single-test campaign already has a durable send record. Review it; creating another test is blocked.');return this.insert(data.requestId,'Single test email',1,[{draftId:null,recipient:data.recipient,name:'Test recipient',subject:data.subject,body:data.body}]);}
 private insert(requestId:string,title:string,limit:number,messages:{draftId:string|null;recipient:string;name:string;subject:string;body:string}[]){
 if(messages.some(m=>/@(example\.(com|org|net)|localhost)$/i.test(m.recipient)))throw Error('Reserved example addresses cannot receive real email. Supply a real address privately in the app.');
 const id=randomUUID(),digest=hash(messages);this.db.exec('BEGIN');try{this.db.prepare('INSERT INTO campaigns(id,request_id,title,state,send_limit,digest,created) VALUES(?,?,?,?,?,?,?)').run(id,requestId,title,'draft',limit,digest,new Date().toISOString());for(const m of messages){const actionId=randomUUID();this.db.prepare('INSERT INTO mail_actions(id,campaign_id,draft_id,recipient,name,subject,body,fingerprint,state,rfc_message_id) VALUES(?,?,?,?,?,?,?,?,?,?)').run(actionId,id,m.draftId,m.recipient,m.name,m.subject,m.body,hash([m.recipient,m.subject,m.body]),'draft',`${actionId}@outreach-workbench.local`);}event(this.db,id,'Campaign review saved. No messages authorized or sent.');this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');if((e as Error).message.includes('UNIQUE'))throw Error('A selected draft or identical recipient/content already has a durable send record. Review the existing campaign; duplicate sending is blocked.');throw e;}return {id};
 }
 authorize(id:string,input:unknown){const data=z.object({digest:z.string(),limit:z.number().int().min(1).max(100),expires:z.number().int(),confirm:z.literal(true)}).parse(input);const c:any=this.db.prepare('SELECT * FROM campaigns WHERE id=?').get(id);if(!c)throw Error('Campaign not found.');if(!['draft','paused'].includes(c.state)){if(['authorized','running'].includes(c.state)&&c.authorized_at&&c.digest===data.digest&&c.send_limit===data.limit)return;throw Error('Campaign is no longer awaiting authorization.');}
 if(this.db.prepare("SELECT id FROM mail_actions WHERE campaign_id=? AND state IN ('sending','uncertain')").get(id))throw Error('Wait for or reconcile in-flight sends before authorizing.');
 if(c.next_retry&&c.next_retry>Date.now())throw Error('Wait until the displayed Gmail retry time.');
 if(c.digest!==data.digest||c.send_limit!==data.limit)throw Error('Review changed. Reload the campaign before authorizing.');if(data.expires<=Date.now()||data.expires>Date.now()+86400000)throw Error('Authorization must expire within the next 24 hours.');const connection=this.gmail.summary();if(!connection.connected||!connection.connectionId)throw Error('Connect Gmail before authorizing.');if(!connection.senderConfigured)throw Error('Configure GMAIL_SENDER_EMAIL to match your authorized account or verified send-as alias.');
 this.db.exec('BEGIN');try{this.db.prepare("UPDATE campaigns SET state='authorized',authorized_at=?,expires=?,connection_id=?,sender=?,reason=NULL,next_retry=NULL WHERE id=?").run(new Date().toISOString(),data.expires,connection.connectionId,connection.sender,id);this.db.prepare("UPDATE mail_actions SET state='queued' WHERE campaign_id=? AND state='draft'").run(id);event(this.db,id,`Authorized Gmail campaign for at most ${c.send_limit} messages; expires ${new Date(data.expires).toISOString()}.`);this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}
 }
 control(id:string,action:string){const c:any=this.db.prepare('SELECT * FROM campaigns WHERE id=?').get(id);if(!c)throw Error('Campaign not found.');if(['completed','cancelled'].includes(c.state)||(c.state==='draft'&&action!=='cancel'))throw Error('This campaign cannot be paused or resumed.');if(action==='resume'){if(!c.authorized_at||c.expires<Date.now())throw Error('Campaign authorization expired. Review and authorize remaining items again.');if(c.next_retry&&c.next_retry>Date.now())throw Error('Wait until the displayed Gmail retry time.');if(this.db.prepare("SELECT id FROM mail_actions WHERE campaign_id=? AND state='uncertain'").get(id))throw Error('Reconcile uncertain outcomes before resuming.');if(this.gmail.summary().connectionId!==c.connection_id)throw Error('Gmail account connection changed. Review and explicitly reauthorize remaining items.');this.db.prepare("UPDATE campaigns SET state='authorized',reason=NULL,next_retry=NULL WHERE id=?").run(id);}else if(action==='pause'||action==='cancel'){this.db.prepare('UPDATE campaigns SET state=?,reason=?,next_retry=NULL WHERE id=?').run(action==='pause'?'paused':'cancelled',action==='pause'?'Paused by you':'Cancelled by you',id);}else throw Error('Unknown campaign action.');event(this.db,id,`Gmail campaign ${action}.`);}
 resolve(id:string,input:unknown){const data=z.object({outcome:z.enum(['sent','not_sent']),note:z.string().trim().min(5).max(500),messageId:z.string().max(200).optional(),confirm:z.literal(true)}).parse(input);const a:any=this.db.prepare('SELECT * FROM mail_actions WHERE id=?').get(id);if(!a||a.state!=='uncertain')throw Error('Only uncertain outcomes can be reconciled.');this.db.prepare('UPDATE mail_actions SET state=?,message_id=?,error=? WHERE id=?').run(data.outcome==='sent'?'sent':'failed',data.messageId||null,`Manually reconciled (${data.outcome}): ${data.note}. Resend remains blocked.`,id);event(this.db,a.campaign_id,'Uncertain Gmail outcome manually reconciled. No resend queued.');}
 pauseAll(reason:string){this.db.prepare("UPDATE campaigns SET state='paused',reason=?,next_retry=NULL WHERE state IN ('authorized','running')").run(reason);}
 async tick(){if(this.busy)return;this.busy=true;try{const c:any=this.db.prepare("SELECT * FROM campaigns WHERE state IN ('authorized','running') ORDER BY created LIMIT 1").get();if(!c)return;
 const pause=(reason:string,next:number|null=null)=>this.db.prepare("UPDATE campaigns SET state='paused',reason=?,next_retry=? WHERE id=? AND state IN ('authorized','running')").run(reason,next,c.id);
 if(c.expires<=Date.now()){pause('Campaign authorization expired. No more sends permitted.');return;}if(this.gmail.summary().connectionId!==c.connection_id||this.gmail.summary().sender!==c.sender){pause('Gmail disconnected, sender or account connection changed. Review before continuing.');return;}
 const a:any=this.db.prepare("SELECT * FROM mail_actions WHERE campaign_id=? AND state='queued' ORDER BY rowid LIMIT 1").get(c.id);if(!a){this.db.prepare("UPDATE campaigns SET state='completed',reason='All authorized actions finished; inspect each outcome.' WHERE id=?").run(c.id);return;}
 const used=Number(this.db.prepare("SELECT count(*) n FROM mail_actions WHERE campaign_id=? AND state IN ('sent','sending','uncertain')").get(c.id)!.n);if(used>=c.send_limit){pause('Campaign sending limit reached.');return;}
 let credentials;try{credentials=await this.gmail.credentials();}catch(e){const err=e as MailError;pause(err.message,err.retryAt||null);return;}
 const current:any=this.db.prepare('SELECT * FROM campaigns WHERE id=?').get(c.id);if(!['authorized','running'].includes(current.state)||current.expires<=Date.now()||this.gmail.summary().connectionId!==credentials.connectionId||credentials.connectionId!==c.connection_id||this.gmail.summary().sender!==c.sender)return;
 this.db.exec('BEGIN');try{this.db.prepare("UPDATE campaigns SET state='running' WHERE id=?").run(c.id);const claim=this.db.prepare("UPDATE mail_actions SET state='sending',attempts=attempts+1,error=NULL WHERE id=? AND state='queued'").run(a.id);if(claim.changes!==1){this.db.exec('ROLLBACK');return;}this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}
 try{const messageId=await this.gmail.deliver({...a,sender:c.sender},credentials.access_token);this.db.prepare("UPDATE mail_actions SET state='sent',message_id=?,error=NULL WHERE id=?").run(messageId,a.id);event(this.db,c.id,`Gmail accepted message for ${a.recipient}.`);}catch(e){const err=e instanceof MailError?e:new MailError('uncertain','Unexpected error after sending began. Reconcile in Gmail Sent.');this.db.prepare('UPDATE mail_actions SET state=?,error=? WHERE id=?').run(err.kind==='uncertain'?'uncertain':err.kind==='auth'||err.kind==='rate_limit'?'queued':'failed',err.message,a.id);pause(err.message,err.retryAt);event(this.db,c.id,err.message);}
 }finally{this.busy=false;}}
}
