import { randomBytes, randomUUID, createCipheriv, createDecipheriv, timingSafeEqual, createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync, renameSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { z } from 'zod';

export const SEND_SCOPE='https://www.googleapis.com/auth/gmail.send';
type Credentials={access_token:string;refresh_token:string;expires:number;connectionId:string;scope:string};
export class MailError extends Error {
 constructor(public kind:'auth'|'rate_limit'|'failed'|'uncertain'|'network',message:string,public retryAt:number|null=null){super(message);this.name='MailError';}
}
export function retryTime(value:string|null){if(value){const seconds=Number(value);if(Number.isFinite(seconds)&&seconds>=0)return Date.now()+Math.max(1,seconds)*1000;const date=Date.parse(value);if(Number.isFinite(date))return Math.max(Date.now()+1000,date);}return Date.now()+30000;}
export class TokenVault {
 constructor(public directory:string){}
 private key(){mkdirSync(this.directory,{recursive:true});const file=join(this.directory,'oauth.key');if(!existsSync(file))writeFileSync(file,randomBytes(32),{flag:'wx',mode:0o600});const key=readFileSync(file);if(key.length!==32)throw Error('Invalid local token encryption key.');return key;}
 read():Credentials|null {const file=join(this.directory,'gmail.enc');if(!existsSync(file))return null;try{const packed=JSON.parse(readFileSync(file,'utf8'));const decipher=createDecipheriv('aes-256-gcm',this.key(),Buffer.from(packed.iv,'base64'));decipher.setAuthTag(Buffer.from(packed.tag,'base64'));const text=Buffer.concat([decipher.update(Buffer.from(packed.data,'base64')),decipher.final()]).toString('utf8');return JSON.parse(text);}catch{throw new MailError('auth','Local Gmail credentials cannot be read. Disconnect and reconnect.');}}
 write(value:Credentials){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',this.key(),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(value)),cipher.final()]);const file=join(this.directory,'gmail.enc');writeFileSync(file+'.tmp',JSON.stringify({iv:iv.toString('base64'),tag:cipher.getAuthTag().toString('base64'),data:encrypted.toString('base64')}),{mode:0o600});renameSync(file+'.tmp',file);}
 clear(){rmSync(join(this.directory,'gmail.enc'),{force:true});rmSync(join(this.directory,'gmail.enc.tmp'),{force:true});}
}
export function encodeMail(action:{recipient:string;subject:string;body:string;rfc_message_id:string;sender?:string}){
 const email=z.string().email().max(254).parse(action.recipient);
 const sender=z.string().email().max(254).parse(action.sender||process.env.GMAIL_SENDER_EMAIL||'');
 if(/[\r\n]/.test(action.subject)||/[\r\n<>]/.test(action.rfc_message_id))throw new MailError('failed','Invalid email header.');
 const chunks:string[]=[];let chunk='';for(const character of action.subject){if(Buffer.byteLength(chunk+character)>42){chunks.push(chunk);chunk='';}chunk+=character;}if(chunk)chunks.push(chunk);
 const subject=chunks.map(v=>`=?UTF-8?B?${Buffer.from(v).toString('base64')}?=`).join('\r\n ');const body=Buffer.from(action.body,'utf8').toString('base64').match(/.{1,76}/g)?.join('\r\n')||'';
 const raw=`From: ${sender}\r\nTo: ${email}\r\nSubject: ${subject}\r\nMessage-ID: <${action.rfc_message_id}>\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: base64\r\n\r\n${body}\r\n`;
 return Buffer.from(raw).toString('base64url');
}
export class Gmail {
 status='Not connected';checked:string|null=null;private pending=new Map<string,{verifier:string;expires:number}>();private refreshing:Promise<Credentials>|null=null;private epoch=0;
 constructor(public vault:TokenVault,public transport:typeof fetch=fetch){}
 configured(){return !!process.env.GOOGLE_CLIENT_ID&&!!process.env.GOOGLE_CLIENT_SECRET;}
 summary(){let value:Credentials|null=null;try{value=this.vault.read();}catch{this.status='Needs reconnect: local token storage error';}const status=value?(this.status==='Not connected'?'OAuth connected; sending unverified':this.status):/^(Connected|OAuth connected|OAuth checked)/.test(this.status)?'Not connected':this.status;return {configured:this.configured(),connected:!!value,connectionId:value?.connectionId||null,status,checked:this.checked,scope:SEND_SCOPE,sender:process.env.GMAIL_SENDER_EMAIL||'',senderConfigured:z.string().email().safeParse(process.env.GMAIL_SENDER_EMAIL).success};}
 begin(){if(!this.configured())throw Error('Configure GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET privately in .env first.');for(const [s,p]of this.pending)if(p.expires<Date.now())this.pending.delete(s);if(this.pending.size>=5)throw Error('Too many pending connections. Wait ten minutes.');const state=randomBytes(32).toString('base64url'),verifier=randomBytes(32).toString('base64url');this.pending.set(state,{verifier,expires:Date.now()+600000});const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,redirect_uri:this.callback(),response_type:'code',scope:SEND_SCOPE,access_type:'offline',prompt:'consent',state,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}).toString();return {url:url.toString(),state};}
 callback(){const expected=`http://localhost:${process.env.PORT||3000}/api/gmail/callback`;const configured=process.env.GOOGLE_REDIRECT_URI||expected;if(configured!==expected)throw Error('GOOGLE_REDIRECT_URI must exactly match '+expected+' and the URI registered in Google Console.');return configured;}
 async complete(state:string,cookie:string,code:string){const pending=this.pending.get(state);if(!pending||pending.expires<Date.now()||state.length!==cookie.length||!timingSafeEqual(Buffer.from(state),Buffer.from(cookie)))throw Error('OAuth state is invalid or expired. Start connection again.');this.pending.delete(state);const epoch=this.epoch;
 const res=await this.transport('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},signal:AbortSignal.timeout(30000),body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!,redirect_uri:this.callback(),grant_type:'authorization_code',code,code_verifier:pending.verifier})});
 if(!res.ok)throw Error('Google could not exchange the authorization code. Start connection again.');const t:any=await res.json();if(!t.access_token||!t.refresh_token||!String(t.scope||'').split(' ').includes(SEND_SCOPE))throw Error('Google did not grant offline Gmail sending access. Reconnect and approve the requested scope.');if(this.epoch!==epoch)throw Error('Connection cancelled.');this.vault.write({access_token:t.access_token,refresh_token:t.refresh_token,expires:Date.now()+Number(t.expires_in||3600)*1000,connectionId:randomUUID(),scope:SEND_SCOPE});this.status='OAuth connected; sending unverified';this.checked=new Date().toISOString();}
 async credentials(force=false):Promise<Credentials>{const current=this.vault.read();if(!current)throw new MailError('auth','Gmail is not connected.');if(!force&&current.expires>Date.now()+60000)return current;if(this.refreshing)return this.refreshing;
 const epoch=this.epoch;this.refreshing=(async()=>{let res:Response;try{res=await this.transport('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},signal:AbortSignal.timeout(30000),body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',grant_type:'refresh_token',refresh_token:current.refresh_token})});}catch{this.status='Network failure while checking Gmail authentication';throw new MailError('network',this.status);}
 if(!res.ok){if(res.status===429){this.status='Authentication check rate limited';throw new MailError('rate_limit',this.status,retryTime(res.headers.get('retry-after')));}this.status='Needs reconnect: Gmail authorization expired or revoked';throw new MailError('auth',this.status);}const t:any=await res.json();if(!t.access_token)throw new MailError('auth','Google returned no access token.');if(this.epoch!==epoch)throw new MailError('auth','Gmail was disconnected.');const next={...current,access_token:t.access_token,refresh_token:t.refresh_token||current.refresh_token,expires:Date.now()+Number(t.expires_in||3600)*1000};this.vault.write(next);this.status='OAuth checked; sending unverified';this.checked=new Date().toISOString();return next;})();try{return await this.refreshing;}finally{this.refreshing=null;}}
 async check(){await this.credentials(true);return this.summary();}
 async disconnect(){this.epoch++;this.pending.clear();let value:Credentials|null=null;try{value=this.vault.read();}catch{this.vault.clear();this.status='Disconnected locally; revoke access in Google Account';return {revoked:false};}this.vault.clear();this.status='Not connected';if(!value)return {revoked:true};try{const res=await this.transport('https://oauth2.googleapis.com/revoke',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},signal:AbortSignal.timeout(15000),body:new URLSearchParams({token:value.refresh_token})});if(!res.ok){this.status='Disconnected locally; revoke access in Google Account';return {revoked:false};}return {revoked:true};}catch{this.status='Disconnected locally; revoke access in Google Account';return {revoked:false};}}
 async deliver(action:Parameters<typeof encodeMail>[0],accessToken:string){let res:Response;try{res=await this.transport('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(30000),body:JSON.stringify({raw:encodeMail(action)})});}catch{throw new MailError('uncertain','Send response was lost. Check Gmail Sent before resolving; automatic resend is blocked.');}
 if(res.status===401){this.status='Needs reconnect: Gmail rejected authorization';throw new MailError('auth',this.status);}
 if(res.status===429) {this.status='Gmail rate limited';throw new MailError('rate_limit',this.status,retryTime(res.headers.get('retry-after')));}
 if(res.status>=500)throw new MailError('uncertain','Gmail server error after send request. Check Gmail Sent; do not resend.');
 if(!res.ok){let reasons='';try{const data:any=await res.json();reasons=data.error?.errors?.map((x:any)=>x.reason).join(' ')||'';}catch{}if(res.status===403&&/rateLimitExceeded|userRateLimitExceeded|dailyLimitExceeded/.test(reasons)){this.status='Gmail sending limit reached';throw new MailError('rate_limit',this.status,retryTime(res.headers.get('retry-after')));}throw new MailError('failed',`Gmail rejected this message (${res.status}). Check account permissions and recipient.`);}
 try{const data:any=await res.json();if(typeof data.id!=='string'||!data.id)throw Error();this.status='Connected: Gmail accepted a send';return data.id;}catch{throw new MailError('uncertain','Gmail accepted the request but returned no usable message ID. Check Sent; do not resend.');}
 }
}
