import { createHash,randomUUID } from 'node:crypto';
import { z } from 'zod';
import { type Store } from './store.js';
import { connectionState,liveEnabled,plan } from './provider.js';
import { selectLeads } from './selection.js';
import { Gmail } from './gmail.js';
import { Supervisor } from './supervisor.js';
import { readFile,mapRows } from './importer.js';
import { checkRepository } from './repository.js';
export const SAMPLE_INSTRUCTION='UAE ke hardware stores select karo aur meri e-commerce website development service ke personalized drafts banao.';
const fingerprint=(parts:unknown[])=>createHash('sha256').update(JSON.stringify(parts)).digest('hex');
export class GuidedSetup {
 running=false;repository:any={status:'Not configured',detail:'Run repository check to inspect installed authentication tools and private origin.',checked:null,pushed:false};
 constructor(public db:Store,public gmail:Gmail,public supervisor:Supervisor){db.prepare("UPDATE setup_checks SET status='attention',detail='Verification interrupted by server restart. Run again.' WHERE status='working'").run();}
 aiContext(){return fingerprint(['setup-v3',process.env.GEMINI_API_KEY||'',process.env.GEMINI_MODEL||'gemini-3.8-flash',process.env.FREE_TIER_CONFIRMED,process.env.AI_DATA_CONSENT,process.env.OUTREACH_LANGUAGE]);}
 gmailContext(){return fingerprint([this.gmail.summary().connectionId,process.env.GOOGLE_CLIENT_ID,this.gmail.summary().sender,this.gmail.callback()]);}
 record(name:string,status:string,detail:string,context:string,mode:string|null=null,taskId:string|null=null){this.db.prepare('INSERT INTO setup_checks VALUES(?,?,?,?,?,?,?) ON CONFLICT(name) DO UPDATE SET status=excluded.status,detail=excluded.detail,checked=excluded.checked,context=excluded.context,mode=excluded.mode,task_id=excluded.task_id').run(name,status,detail,new Date().toISOString(),context,mode,taskId);}
 private evidence(name:string,context:string){const row:any=this.db.prepare('SELECT * FROM setup_checks WHERE name=?').get(name);if(!row||row.context!==context)return null;return {status:row.status,detail:row.detail,checked:row.checked,mode:row.mode,taskId:row.task_id};}
 summary(origin:string){const ai=connectionState(),mail=this.gmail.summary();let callback='';try{callback=this.gmail.callback();}catch{}
 const actualCallback=origin+'/api/gmail/callback',callbackMatches=callback===actualCallback;const classify=(proof:any,configured:boolean)=>!configured?'Not configured':proof?.status==='verified'?'Verified':proof?.status==='attention'?'Needs attention':'Configured but unverified';
 const aiProof=this.evidence('ai',this.aiContext()),workflow=this.evidence('workflow',this.aiContext()),gmailProof=callback?this.evidence('gmail',this.gmailContext()):null;
 const aiStatus=!process.env.GEMINI_API_KEY?'Not configured':!liveEnabled()||!['not_checked','connected'].includes(ai.code)?'Needs attention':classify(aiProof,true);
 const gmailStatus=!mail.configured?'Not configured':!callbackMatches||/failed|error|Needs reconnect|Network|rate limit/i.test(mail.status)?'Needs attention':classify(gmailProof,mail.configured);
 const latestTest:any=this.db.prepare("SELECT c.id,a.state,a.message_id,a.error FROM campaigns c JOIN mail_actions a ON a.campaign_id=c.id WHERE c.title='Single test email' AND c.send_limit=1 ORDER BY c.created DESC LIMIT 1").get();
 return {steps:[{id:'ai',title:'Configure free-tier AI',status:aiStatus,detail:aiProof?.detail||ai.status,checked:aiProof?.checked||ai.checked,next:'Privately edit .env: GEMINI_API_KEY, FREE_TIER_CONFIRMED=true after console billing review, AI_DATA_CONSENT=true after privacy review. Restart, then check connection. Billing is not verified by this check.'},
 {id:'gmail',title:'Connect Gmail',status:gmailStatus,detail:gmailProof?.detail||mail.status,checked:gmailProof?.checked||mail.checked,next:'Configure Google OAuth Web client and GMAIL_SENDER_EMAIL privately. Register the exact callback below, consent in Google, then check authentication. Send-only scope; no email is sent by the check.'},
 {id:'workflow',title:'Verify a draft-only workflow',status:workflow?.status==='verified'&&workflow.mode==='live'?'Verified':workflow?.status==='attention'?'Needs attention':workflow?'Configured but unverified':'Not configured',detail:workflow?.detail||'No live sample workflow has been verified.',checked:workflow?.checked||null,mode:workflow?.mode||null,taskId:workflow?.taskId||null,next:'Run the labeled UAE hardware-store sample. Demo verifies deterministic behavior only; Live requires configured AI and verifies actual requests and saved drafts.'},
 {id:'test',title:'Optionally authorize one test email',status:latestTest?.state==='sent'?'Verified':latestTest&&['failed','uncertain'].includes(latestTest.state)?'Needs attention':latestTest?'Configured but unverified':'Not configured',detail:latestTest?.state==='sent'?'Gmail accepted this one-email action; inbox delivery is not guaranteed.':latestTest?'Review this single-email campaign and its actual outcome; saving a review is not authorization.':'Optional. No real recipient or test send has been authorized.',messageId:latestTest?.message_id||null,next:'Supply a recipient privately in Gmail, save the exact subject/body review, then explicitly authorize that single-email campaign only when ready.'},
 {id:'github',title:'Connect a private GitHub repository',...this.repository}],callback:{expected:callback,application:actualCallback,matches:callbackMatches,registrationVerified:!!callback&&this.evidence('callback',this.gmailContext())?.status==='verified',note:'A matching local value does not prove Google registration. Successful consent code exchange and authentication check provide the available end-to-end callback evidence.'},working:this.running,sampleInstruction:SAMPLE_INSTRUCTION,realSendingEnabled:process.env.GMAIL_ENABLE_SENDING==='true'};
 }
 async repositoryCheck(){this.repository=await checkRepository();return this.repository;}
 async verifyWorkflow(mode:'demo'|'live',requestId:string=randomUUID()){
 const prior:any=this.db.prepare('SELECT id,state,mode FROM tasks WHERE request_id=?').get(requestId);if(prior){if(prior.mode!==mode||prior.state!=='completed')throw Error('Prior sample task is not completed in this mode. Inspect it before rerunning.');return {ok:true,mode,taskId:prior.id,drafts:2,duplicate:true};}
 if(this.running)throw Error('A setup workflow check is already running.');if(mode==='live'&&!liveEnabled())throw Error('Configure free-tier AI privately and restart before live verification.');this.running=true;const context=this.aiContext();let taskId:string|null=null;
 try{this.record('workflow','working',`${mode} sample workflow is running; no messages will be sent.`,context,mode);
 const run=randomUUID();const csv='name,email,company,city,country,industry\nAyesha Sample,ayesha-'+run+'@example.com,Desert Hardware Sample,Dubai,UAE,hardware\nOmar Sample,omar-'+run+'@example.com,Gulf Tools Sample,Abu Dhabi,United Arab Emirates,hardware stores\nSara Sample,sara-'+run+'@example.com,Gulf Software Sample,Dubai,UAE,software\nBilal Sample,bilal-'+run+'@example.com,Karachi Hardware Sample,Karachi,Pakistan,hardware';
 const parsed=await readFile('guided-setup-sample.csv',Buffer.from(csv));const mapped=mapRows(parsed.rows,{name:0,email:1,company:2,city:3,country:4,industry:5},new Set());if(mapped.errors.length)throw Error('Sample import validation failed.');const ids:string[]=[];
 this.db.exec('BEGIN');try{for(const lead of mapped.valid){const id=randomUUID();ids.push(id);this.db.prepare('INSERT INTO leads(id,name,email,company,city,notes,source,country,industry) VALUES(?,?,?,?,?,?,?,?,?)').run(id,lead.name,lead.email,lead.company,lead.city,'Synthetic setup sample; never send','Guided setup sample (do not send)',lead.country,lead.industry);}this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}
 taskId=randomUUID();const now=new Date().toISOString();this.db.prepare('INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?)').run(taskId,requestId,SAMPLE_INSTRUCTION,mode,'needs_user','Planning your request',null,now);this.db.prepare('INSERT INTO task_plans(task_id,scope) VALUES(?,?)').run(taskId,JSON.stringify(ids));this.db.prepare('INSERT INTO chat VALUES(?,?,?,?)').run(randomUUID(),'user',`[${mode.toUpperCase()} SETUP SAMPLE] ${SAMPLE_INSTRUCTION}`,now);this.record('workflow','working','Planning labeled samples.',context,mode,taskId);await this.supervisor.planTask(taskId);const planningTask:any=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);if(this.db.prepare('SELECT task_id FROM task_plans WHERE task_id=?').get(taskId))throw Error(planningTask.reason);const selected:any[]=this.db.prepare('SELECT lead_id FROM steps WHERE task_id=?').all(taskId);if(selected.length!==2||selected.some(l=>!ids.slice(0,2).includes(l.lead_id)))throw Error('Selection check failed: expected only the two UAE hardware samples.');
 this.record('workflow','working','Selection passed; waiting for persisted personalized sample drafts.',context,mode,taskId);this.supervisor.control(taskId,'start');const deadline=Date.now()+180000;let task:any;
 do{await new Promise(r=>setTimeout(r,300));task=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(taskId);}while(['running','queued'].includes(task.state)&&Date.now()<deadline);
 if(task.state!=='completed'){if(['running','queued'].includes(task.state))this.supervisor.control(taskId,'pause');throw Error(`Draft generation: ${task.reason||task.state}. Resume the existing task; completed drafts remain saved.`);}
 const drafts:any[]=this.db.prepare('SELECT d.*,l.name,l.company FROM drafts d JOIN leads l ON l.id=d.lead_id WHERE task_id=?').all(taskId);
 if(drafts.length!==2||drafts.some(d=>d.mode!==mode||!d.body.toLowerCase().includes(d.name.split(' ')[0].toLowerCase())||!d.body.toLowerCase().includes(d.company.toLowerCase())||!/e.?commerce|e.?kommerce/i.test(d.body)||!/website|web.?site/i.test(d.body)||(process.env.OUTREACH_LANGUAGE!=='english'&&!/\b(aap|ke|liye|hain|salam|Assalam)\b/i.test(d.body))))throw Error('Draft validation failed: expected saved mode, lead personalization and the offered website service.');
 this.record('workflow',mode==='live'?'verified':'demo_passed',`${mode==='live'?'Real live AI':'Deterministic demo'}: two UAE hardware leads selected; two personalized website-service drafts persisted. ${mode==='demo'?'Live verification remains pending. ':''}No email sent.`,context,mode,taskId);return {ok:true,mode,taskId,drafts:2};
 }catch(e){this.record('workflow','attention',e instanceof Error?e.message:'Sample workflow check failed.',context,mode,taskId);throw e;}finally{this.running=false;}}
}
