import React from 'react';
export function ChatResults({state,busy,act,api,mode}:{state:any;busy:boolean;act:(fn:()=>Promise<unknown>)=>unknown;api:(path:string,body?:unknown)=>Promise<any>;mode:string}){
 const csv=(id:string)=>act(()=>api('chat',{requestId:crypto.randomUUID(),text:`CSV result ${id}`,mode}));
 return <section aria-label="Chat tool results">
 {(state.chatRequests||[]).filter((r:any)=>!r.task_id&&['queued','running','paused'].includes(r.state)).map((r:any)=><article className="progressCard" key={r.id} role="status"><strong>{r.state==='paused'?'Request paused':'Understanding your request'}</strong><p>{r.reason}</p>{r.retry_at&&<p>Retry after {new Date(r.retry_at).toLocaleString()}</p>}<div className="row">{r.state==='paused'&&<button disabled={busy||r.retry_at>Date.now()} onClick={()=>act(()=>api(`chat-requests/${r.id}/resume`,{}))}>Resume</button>}<button className="secondary" disabled={busy} onClick={()=>act(()=>api(`chat-requests/${r.id}/cancel`,{}))}>Cancel</button></div></article>)}
 {(state.resultSets||[]).map((set:any)=><article className="resultCard" key={set.id}><div className="sectionHead"><h3>{set.title}</h3><span className="tag">{set.origin==='imported'?'Imported lead filtering':'Public source retrieval'} · {set.state}</span></div><p>{set.rows.length} actual result(s){set.requested?` / ${set.requested} requested`:''}. {set.reason}</p><small>Result ID: {set.id}</small>
 {set.origin!=='imported'&&<p className="muted">Source-backed candidates, not independent business verification. Unknown contacts stay unknown. Phone listing does not establish WhatsApp availability.</p>}
 <div className="tableWrap" tabIndex={0} aria-label={`${set.title} results table`}><table><thead><tr>{['Company','Location','Website','Business email','Business phone','Sources / retrieved'].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{set.rows.map((r:any,i:number)=><tr key={i}><td>{r.name}</td><td>{r.location||'Unknown'}</td><td>{r.website?<a href={r.website} target="_blank" rel="noopener noreferrer">Website</a>:'Unknown'}</td><td>{r.email||'Unknown'}</td><td>{r.phone||'Unknown'}</td><td>{r.sources.length?r.sources.map((url:string)=><a key={url} href={url} target="_blank" rel="noopener noreferrer">Source<br/></a>):'Local import'}<small>{new Date(r.retrieved_at).toLocaleString()}</small></td></tr>)}</tbody></table></div>
 <div className="row">{set.export?<a className="download" href={`/api/exports/${set.export.id}.csv`} download={set.export.filename}>Download CSV snapshot</a>:<button disabled={busy||!['completed','partial'].includes(set.state)} onClick={()=>csv(set.id)}>Create CSV</button>}{set.origin!=='imported'&&set.rows.length>0&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{const r=await api(`results/${set.id}/save-leads`,{});if(!r.saved)throw Error(`No new leads saved; ${r.skipped} missing-email or duplicate rows. Results remain available here.`);})}>Save leads with known emails</button>}</div>
 </article>)}
 </section>;
}
