import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';
import { SetupPanel } from './SetupPanel';
import { GmailConnection, GmailCampaigns } from './GmailPanel';
import { enterAction } from './chat-input';
async function api(path: string, body?: unknown) { const r = await fetch('/api/' + path, body === undefined ? {signal:AbortSignal.timeout(10000)} : { signal:AbortSignal.timeout(105000), method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok)
    throw Error(d.error || 'Request failed'); return d; }
const labels: Record<string, string> = { queued: 'Ready', running: 'Working', paused: 'Paused', needs_user: 'Needs your help', completed: 'Completed', failed: 'Needs your help', cancelled: 'Cancelled' };
function App() {
    const [tab, setTab] = useState('Setup'), [state, setState] = useState<any>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [text, setText] = useState(''), [mode, setMode] = useState('demo'), [online, setOnline] = useState(true), [preview, setPreview] = useState<any>(null), [mapping, setMapping] = useState<Record<string, number>>({}), [result, setResult] = useState<any>(null), [editing, setEditing] = useState<any>(null);
    const modeInitialized = useRef(false), refreshing = useRef(false);
    const lock = useRef(false), composing = useRef(false), request = useRef<{
        text: string;
        id: string;
        mode: string;
    } | null>(null);
    const refresh = async () => { if(refreshing.current)return;refreshing.current=true;try {
        const next=await api('state');setState(next);
        if(!modeInitialized.current){modeInitialized.current=true;setMode(next.connection.configured?'live':'demo');}
        setOnline(true);
    }
    catch {
        setOnline(false);
    } finally { refreshing.current=false; } };
    useEffect(() => { void refresh(); const t = setInterval(refresh, 1500); return () => clearInterval(t); }, []);
    async function act(fn: () => Promise<unknown>) { if (lock.current)
        return; lock.current = true; setBusy(true); setError(''); try {
        await fn();
        await refresh();
    }
    catch (e) {
        setError((e as Error).message);
    }
    finally {
        lock.current = false;
        setBusy(false);
    } }
    async function send() { if (!text.trim() || composing.current || lock.current)
        return; const value = text.trim(); await act(async () => { if (!request.current || request.current.text !== value || request.current.mode !== mode)
        request.current = { text: value, id: crypto.randomUUID(), mode }; await api('chat', { text: value, requestId: request.current.id, mode }); setText(''); request.current = null; }); }
    async function upload(file: File) { await act(async () => { setResult(null); setPreview(null); if (file.size > 2000000)
        throw Error('Maximum upload size is 2 MB.'); const bytes = new Uint8Array(await file.arrayBuffer()); let bin = ''; for (const b of bytes)
        bin += String.fromCharCode(b); const p = await api('import/preview', { name: file.name, content: btoa(bin) }); setPreview(p); const m: Record<string, number> = {}; for (const f of ['name', 'email', 'company', 'city', 'country', 'industry', 'notes'])
        m[f] = p.headers.findIndex((h: string) => h.toLowerCase() === f); setMapping(m); }); }
    if (!state)
        return <main><h1>Outreach Workbench</h1><p role="status">{online ? 'Loading your workspace…' : 'Cannot reach the local server. Start it and refresh.'}</p></main>;
    return <div className="shell"><aside><a className="brand" href="#" onClick={() => setTab('Chat')}>ow<span>Outreach<br />Workbench</span></a><p className="eyebrow">PERSONAL WORKSPACE</p><nav aria-label="Main navigation">{['Setup', 'Chat', 'Leads', 'Tasks', 'Gmail', 'Connections', 'Settings'].map((t, i) => <button key={t} className={tab === t ? 'active' : ''} onClick={() => setTab(t)} aria-current={tab === t ? 'page' : undefined}><span>{['✦', '◉', '▤', '↗', '⚙'][i]}</span>{t}{t === 'Tasks' && <small>{state.tasks.length}</small>}</button>)}</nav><div className="asideNote"><span className="dot"/> Local workspace<p>Your drafts and progress stay on this laptop. Sending needs a reviewed campaign authorization.</p></div></aside><div className="workspace"><header><div><span className="eyebrow">YOUR OUTREACH, UNDER CONTROL</span><h1>{tab}</h1></div><div className="status"><span className="dot"/>{online ? 'Local server online' : 'Reconnecting…'}<strong>{mode === 'demo' ? 'Demo mode' : 'Live AI selected'}</strong></div></header><main>
 {error && <div className="error" role="alert">{error}<button onClick={() => setError('')} aria-label="Dismiss error">×</button></div>}
 {!online && <div className="error" role="status">Connection lost. Progress is persisted; reconnecting to retrieve it.</div>}
 <div className="stats"><article><span>Leads in workspace</span><strong>{state.leads.length}</strong></article><article><span>Saved drafts</span><strong>{state.drafts.length}</strong></article><article><span>Active tasks</span><strong>{state.tasks.filter((t: any) => ['running', 'queued'].includes(t.state)).length}</strong></article><article><span>Messages sent</span><strong>{state.mailActions.filter((a:any)=>a.state==='sent').length} <small>Gmail</small></strong></article></div>
 {tab === 'Setup' && state.setup && <SetupPanel {...{state,busy,act,api}} navigate={setTab}/>}
 {tab === 'Chat' && <><section className="setup"><div><span className="eyebrow">START HERE</span><h2>Turn your lead list into a useful first draft.</h2><p>Import a list, describe who to reach, then review and start your task.</p></div><div className="row"><button onClick={() => setTab('Leads')}>Import leads</button><button className="secondary" disabled={busy} onClick={() => act(() => api('demo'))}>Load demo samples</button><button className="secondary" onClick={() => setTab('Setup')}>Set up live AI</button></div></section><div className="columns"><section className="card chat"><div className="sectionHead"><h2>Plan with your assistant</h2><span className="tag">{mode === 'demo' ? 'Deterministic demo' : 'Gemini · ' + state.connection.status}</span></div><p className="muted">Live supports conversation and English/Roman Urdu lead instructions. Drafts need review and Start drafts. Chat cannot browse or send messages.</p><label htmlFor="chatMode">Chat mode</label><select id="chatMode" value={mode} onChange={e => setMode(e.target.value)} disabled={busy}><option value="demo">Demo - limited examples, no live conversation</option><option value="live" disabled={!state.connection.configured}>Live - {state.connection.model}</option></select><div className="messages" aria-live="polite">{!state.chat.length && <div className="empty"><h3>What would you like to work on?</h3><p>Try “Karachi ke 2 leads ke liye outreach drafts banao”.</p><button className="secondary" onClick={() => setText('Karachi ke 2 leads ke liye outreach drafts banao')}>Use this example</button></div>}{state.chat.map((m: any) => <article key={m.id} className={'message ' + m.role}><small>{m.role === 'user' ? 'You' : 'Assistant'}</small><p>{m.text}</p></article>)}</div><form onSubmit={e => { e.preventDefault(); void send(); }}><label htmlFor="instruction">Your instruction</label><textarea id="instruction" value={text} maxLength={4000} onChange={e => setText(e.target.value)} onCompositionStart={() => { composing.current = true; }} onCompositionEnd={() => { composing.current = false; }} onKeyDown={e => { const action=enterAction(e.shiftKey,e.nativeEvent.isComposing,composing.current,e.keyCode,e.repeat);if (e.key === 'Enter' && action!=='edit') {
        e.preventDefault();
        if (action==='submit')
            void send();
    } }} placeholder="Ask a question or describe the lead drafts you need..."/><div className="composerFooter"><span>Enter to send · Shift+Enter for a new line</span><button disabled={busy || !text.trim() || !online}>{busy ? 'Submitting...' : 'Send'}</button></div></form><h3>Chat progress and results</h3>{state.tasks.slice(0,5).map((t:any)=><article key={t.id} className="lead" aria-live="polite"><strong>{labels[t.state]} - {t.mode}</strong><p>{t.reason || `${t.done} of ${t.total} drafts saved`}</p>{t.planning && <p>Waiting for AI classification/planning (bounded request and retry budget).</p>}{t.next_retry && <p>Retry after {new Date(t.next_retry).toLocaleString()}</p>}{t.state==='paused' && (t.planning||t.total>0) && <button disabled={busy} onClick={()=>act(()=>api(`tasks/${t.id}/${t.done?'resume':'start'}`,{}))}>{t.planning?'Resume planning':t.done?'Resume drafts':'Start drafts'}</button>}{!['completed','cancelled','failed'].includes(t.state)&&<button className="secondary" disabled={busy} onClick={()=>act(()=>api(`tasks/${t.id}/cancel`,{}))}>Cancel</button>}{state.drafts.filter((d:any)=>d.task_id===t.id).map((d:any)=><details key={d.id}><summary>Saved {d.mode} draft - {d.subject}</summary><p className="draft">{d.body}</p></details>)}</article>)}</section><Activity events={state.events}/></div></>}
 {tab === 'Leads' && <><section className="card"><div className="sectionHead"><h2>Import your prospects</h2><span className="tag">CSV / XLSX · up to 2 MB</span></div><p>First worksheet only. Up to 1,000 rows. Formulas are blocked; duplicate emails are skipped.</p><label htmlFor="file">Choose a lead list</label><input id="file" type="file" accept=".csv,.xlsx" disabled={busy} onChange={e => { const f = e.target.files?.[0]; if (f)
        void upload(f); e.target.value = ''; }}/>{preview && <><h3>Map your columns</h3><div className="mapping">{['name', 'email', 'company', 'city', 'country', 'industry', 'notes'].map(f => <label key={f}>{f}{['name', 'email'].includes(f) ? ' *' : ''}<select value={mapping[f]} onChange={e => { setMapping({ ...mapping, [f]: Number(e.target.value) }); setResult(null); }}><option value={-1}>Not mapped</option>{preview.headers.map((h: string, i: number) => <option value={i} key={i}>{h}</option>)}</select></label>)}</div><h3>Raw preview · first 5 rows of {preview.rows.length}</h3><div className="tableWrap"><table><thead><tr>{preview.headers.map((h: string, i: number) => <th key={i}>{h}</th>)}</tr></thead><tbody>{preview.rows.slice(0, 5).map((r: string[], i: number) => <tr key={i}>{r.map((c, j) => <td key={j}>{c}</td>)}</tr>)}</tbody></table></div><div className="row"><button className="secondary" disabled={busy} onClick={() => act(async () => setResult(await api('import/validate', { id: preview.id, mapping })))}>Validate mapping</button><button disabled={busy || !result || !result.valid.length} onClick={() => act(async () => { const r = await api('import/commit', { id: preview.id, mapping }); setResult({ ...r, imported: true }); setPreview(null); })}>Import valid rows</button></div></>}{result && <div role="status"><p>{result.imported ? 'Imported' : 'Ready to import'}: {result.valid.length} · Skipped: {result.errors.length}</p>{result.errors.length > 0 && <details><summary>Row-level errors</summary><ul>{result.errors.map((e: any) => <li key={e.row}>Row {e.row}: {e.message}</li>)}</ul></details>}</div>}</section><section className="card"><h2>Your leads</h2>{!state.leads.length ? <p>No leads yet. Import a file or load samples from Chat.</p> : <div className="leadGrid">{state.leads.map((l: any) => <article className="lead" key={l.id}><h3>{l.name}</h3><p>{l.email}</p><p>{l.company} · {l.city}</p><small>Source: {l.source}</small><button className="secondary" onClick={() => setEditing({ ...l })}>Edit lead</button>{state.drafts.filter((d: any) => d.lead_id === l.id).map((d: any) => <details key={d.id}><summary>Saved {d.mode} draft · {d.subject}</summary><p className="draft">{d.body}</p></details>)}</article>)}</div>}</section></>}
 {tab === 'Tasks' && <div className="columns"><section>{!state.tasks.length && <section className="card empty"><h2>No tasks yet</h2><p>Create a plan in Chat after importing leads.</p></section>}{state.tasks.map((t: any) => <section className="card" key={t.id}><div className="sectionHead"><h2>{labels[t.state]}</h2><span className="tag">{t.mode} · draft only</span></div><p className="draft">{t.instruction}</p><progress value={t.done} max={Math.max(1, t.total)}/><p>{t.done} of {t.total} drafts saved · {t.total - t.done} pending</p>{t.reason && <p>{t.reason}</p>}{t.next_retry && <p>Next retry: {new Date(t.next_retry).toLocaleString()} (not a quota reset estimate)</p>}<details><summary>Selected leads and steps</summary>{state.steps.filter((s: any) => s.task_id === t.id).map((s: any) => <p key={s.lead_id}>{state.leads.find((l: any) => l.id === s.lead_id)?.name}: {s.state} · attempts {s.attempts}{s.error ? ' · ' + s.error : ''}</p>)}</details><div className="row">{(t.state === 'paused' || (t.state === 'needs_user' && !t.planning)) && (t.total > 0 || t.planning) && <button disabled={busy || !!(t.next_retry && t.next_retry > Date.now())} onClick={() => act(() => api(`tasks/${t.id}/${t.done ? 'resume' : 'start'}`, {}))}>{t.planning ? 'Resume planning' : t.done ? 'Resume' : 'Start drafts'}</button>}{(['queued', 'running'].includes(t.state) || (t.planning && t.state === 'needs_user')) && <button disabled={busy} onClick={() => act(() => api(`tasks/${t.id}/pause`, {}))}>Pause</button>}{!['completed', 'cancelled'].includes(t.state) && <button className="secondary" disabled={busy} onClick={() => act(() => api(`tasks/${t.id}/cancel`, {}))}>Cancel</button>}</div></section>)}</section><Activity events={state.events}/></div>}
 {tab === 'Connections' && <section className="card"><h2>Your connections</h2><div className="leadGrid"><article className="lead"><h3>Gemini AI</h3><span className="tag">{state.connection.status}</span><p>{state.connection.checked ? 'Last checked: ' + new Date(state.connection.checked).toLocaleString() : 'No live request verified yet.'}</p><button disabled={busy} onClick={() => act(() => api('health', {}))}>Check live connection</button></article><GmailConnection {...{state,busy,act,api}}/>{['WhatsApp', 'LinkedIn'].map(n => <article className="lead" key={n}><h3>{n}</h3><span className="tag">Not implemented</span><p>Supported authentication and sending are planned for a later phase.</p></article>)}</div></section>}
 {tab === 'Gmail' && <GmailCampaigns {...{state,busy,act,api}}/>}
 {tab === 'Settings' && <section className="card settings"><h2>Choose your working mode</h2><label htmlFor="mode">AI mode</label><select id="mode" value={mode} onChange={e => setMode(e.target.value)}><option value="demo">Demo · deterministic sample behavior</option><option value="live" disabled={!state.connection.configured}>Live · Gemini free tier</option></select><p>Demo understands a small set of examples: Karachi, Lahore, Islamabad, UAE hardware stores, a numeric limit, and common Roman Urdu words. It does not interpret arbitrary instructions.</p><p>Configured Gemini model: <code>{state.connection.model}</code>. Change GEMINI_MODEL privately and restart; models never switch automatically.</p><h3>Private live AI setup</h3><ol><li>Open Google AI Studio and verify your project is eligible for free API use with no billing enabled.</li><li>Copy <code>.env.example</code> to <code>.env</code> in this project and edit it locally. Put your key only in that file.</li><li>Set <code>FREE_TIER_CONFIRMED=true</code> and <code>AI_DATA_CONSENT=true</code> only after checking the account and agreeing to share selected lead fields with Gemini. Free-tier content may be used to improve Google's products.</li><li>Restart the local server, check the connection, then select Live above.</li></ol><p>The app cannot verify billing status from an API key. It never enables billing or switches providers. API quotas and free availability are limited.</p><p>Keep this app local. Login, cloud hosting, and voice input are future work. Gmail sending requires private OAuth setup and an explicitly authorized campaign.</p></section>}
 {editing && <div className="modal"><section role="dialog" aria-modal="true" aria-labelledby="editTitle" className="card"><h2 id="editTitle">Edit lead</h2><form onSubmit={e => { e.preventDefault(); void act(async () => { await api('leads/edit', editing); setEditing(null); }); }}>{['name', 'email', 'company', 'city', 'country', 'industry', 'notes'].map(f => <label key={f}>{f}<input autoFocus={f === 'name'} type={f === 'email' ? 'email' : 'text'} required={['name', 'email'].includes(f)} maxLength={f === 'notes' ? 2000 : 300} value={editing[f]} onChange={e => setEditing({ ...editing, [f]: e.target.value })}/></label>)}<div className="row"><button disabled={busy}>Save changes</button><button type="button" className="secondary" onClick={() => setEditing(null)}>Close</button></div></form></section></div>}
 </main><footer>Local-first · Campaign authorization required for sending · {mode === 'demo' ? 'Demo behavior is not live AI' : 'Live requests use your configured Gemini project'}</footer></div></div>;
}
function Activity({ events }: {
    events: any[];
}) { return <section className="card activity"><div className="sectionHead"><h2>Live activity</h2><span className="dot"/></div><p className="muted">A clear view of what has happened.</p>{!events.length ? <p>No activity yet. Your next step will appear here.</p> : events.map(e => <article key={e.id}><small>{new Date(e.created).toLocaleTimeString()}</small><p>{e.text}</p></article>)}</section>; }
createRoot(document.getElementById('root')!).render(<App />);
