import React,{useRef} from 'react';
type Props={state:any;busy:boolean;act:(fn:()=>Promise<unknown>)=>Promise<void>;api:(path:string,body?:unknown)=>Promise<any>;navigate:(tab:string)=>void};
export function SetupPanel({state,busy,act,api,navigate}:Props){const request=useRef<{id:string;mode:string}|null>(null);const setup=state.setup;
 async function workflow(mode:string){await act(async()=>{if(request.current?.mode!==mode)request.current={id:crypto.randomUUID(),mode};await api('setup/workflow',{mode,requestId:request.current!.id});request.current=null;});}
 const links:Record<string,[string,string][]>={ai:[['Google AI Studio','https://aistudio.google.com/'],['Gemini pricing and free tier','https://ai.google.dev/gemini-api/docs/pricing'],['Google Cloud billing console','https://console.cloud.google.com/billing']],gmail:[['Google OAuth clients','https://console.cloud.google.com/auth/clients'],['Gmail API library','https://console.cloud.google.com/apis/library/gmail.googleapis.com'],['Official OAuth setup','https://developers.google.com/identity/protocols/oauth2/web-server']],github:[['Create repository — choose Private','https://github.com/new'],['Supported Git authentication','https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github']]};
 return <><section className="setup"><h2>Your guided setup</h2><p>Configuration values do not count as a passed connection check. Verified means the recorded backend check passed at the time shown; it does not guarantee future availability, billing status, or delivery.</p><p>Keep keys and client secrets only in the private <code>.env</code> file. Do not enter them in chat, browser storage, or source files.</p><details><summary>Minimum private local setup</summary><pre className="instructions">{`Set-Location 'M:\\Local Ai agent'\n# Copy only if .env does not already exist\nif (!(Test-Path -LiteralPath .env)) { Copy-Item .env.example .env }\nnotepad .env\n# Stop the existing server with Ctrl+C, then restart\nnpm.cmd run dev`}</pre><p>For AI, fill GEMINI_API_KEY. Set FREE_TIER_CONFIRMED=true only after reviewing the project's unbilled tier in AI Studio and Cloud Console; successful AI requests cannot prove this. Set AI_DATA_CONSENT=true only after privacy review. For Gmail, fill GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET and GMAIL_SENDER_EMAIL. Leave GMAIL_ENABLE_SENDING=false.</p></details></section>
 {setup.steps.map((step:any,index:number)=><section className="card" key={step.id}><div className="sectionHead"><h2>{index+1}. {step.title}</h2><span className={'tag '+(step.status==='Needs attention'?'attention':'')}>{step.status}</span></div><p>{step.detail}</p>{step.checked&&<small>Last recorded check: {new Date(step.checked).toLocaleString()}</small>}{step.mode&&<p><strong>{step.mode==='live'?'Live Gemini evidence':'Demo evidence only'}</strong></p>}<p>{step.next}</p>{links[step.id]?.map(([label,url])=><p key={url}><a href={url} target="_blank" rel="noreferrer">{label} ↗</a></p>)}
 {step.id==='ai'&&<button disabled={busy} onClick={()=>act(()=>api('health',{}))}>Check actual AI connection</button>}
 {step.id==='gmail'&&<><p>Application callback: <code>{setup.callback.application}</code></p><p>Configured callback: <code>{setup.callback.expected||'Invalid local configuration'}</code> · {setup.callback.matches?'Local values match':'Mismatch — open localhost and check PORT / GOOGLE_REDIRECT_URI'}</p><p>{setup.callback.registrationVerified?'Google callback exchange evidence recorded.':'Google redirect registration has not been verified by a successful callback exchange.'}</p><p>Register the exact callback in Google Console. Only gmail.send is requested. Complete Google consent yourself.</p><div className="row"><button disabled={busy||!state.gmail.configured||!setup.callback.matches} onClick={()=>act(async()=>{const result=await api('gmail/connect',{});window.location.assign(result.url);})}>Connect or reconnect Gmail</button><button className="secondary" disabled={busy||!state.gmail.connected} onClick={()=>act(()=>api('gmail/check',{}))}>Check authentication only</button></div></>}
 {step.id==='workflow'&&<><blockquote>{setup.sampleInstruction}</blockquote><p>The check imports four visibly labeled samples, selects the two UAE hardware businesses, and verifies stored personalized website-service drafts. It plans from the instruction, not your full imported database. Samples cannot be emailed.</p><div className="row"><button className="secondary" disabled={busy||setup.working} onClick={()=>workflow('demo')}>Run labeled demo check</button><button disabled={busy||setup.working||!state.connection.configured} onClick={()=>workflow('live')}>Run real live sample check</button><button className="secondary" onClick={()=>navigate('Tasks')}>Inspect saved task/drafts</button></div>{setup.working&&<p role="status">Checking selection and persisted drafts… No mail will be sent.</p>}<p>After key setup, also run <code>node scripts/verify-live.mjs</code> for the isolated live verification. Do not treat demo success as live AI verification.</p></>}
 {step.id==='test'&&<><p>{setup.realSendingEnabled?'Sending flag is enabled; a separate explicit one-recipient authorization is still required.':'Real sending is disabled. Leave it disabled until you intend the optional real test.'}</p>{step.messageId&&<p>Gmail message ID: <code>{step.messageId}</code></p>}<button className="secondary" onClick={()=>navigate('Gmail')}>Review exact recipient, subject and body</button><p>Saving the single-test form sends nothing. Review all fields, then check the explicit authorization box. One durable test campaign is allowed; uncertain sends are blocked from retry.</p></>}
 {step.id==='github'&&<><p>GitHub CLI: {step.tools?.githubCLI?'installed':'not detected'} · Git Credential Manager: {step.tools?.credentialManager?'installed':'not checked / not detected'}</p>{step.url&&<p>Selected repository: <a href={step.url} target="_blank" rel="noreferrer">{step.url}</a></p>}<p>{step.audit?.detail||'Tracked files and history have not yet been inspected in this server session.'}</p><button disabled={busy} onClick={()=>act(()=>api('setup/repository',{}))}>Inspect Git tools, history and private remote</button><details><summary>Connect an existing private repository yourself</summary><pre className="instructions">{`node scripts/verify-history.mjs\ngit remote add origin https://github.com/YOUR_ACCOUNT/YOUR_PRIVATE_REPOSITORY.git\n# Authenticate through installed Git Credential Manager\n# Confirm repository is Private in GitHub before pushing\ngit push -u origin main\ngit ls-remote origin refs/heads/main`}</pre><p>If GitHub CLI is already available, use <code>gh auth login --web</code> and recheck. Without it, repository privacy remains unverified by the app; check GitHub yourself. This screen never creates a repository or pushes.</p></details></>}
 </section>)}
 <section className="card"><h2>Browser checks · Unverified</h2><p>These are manual actions until browser checks are actually performed. Do not authorize a real email while testing the UI.</p><ol><li>Resize to 375, 768 and 1440 pixels. Visit each tab; check navigation, previews and forms for horizontal page overflow.</li><li>In Chat, press Enter once and then Shift+Enter. Confirm one request and a newline respectively. Try empty input, held Enter and rapid clicks while pending; confirm one task.</li><li>Use IME input: Enter must finish composition without sending. Then send deliberately.</li><li>Navigate with Tab/Shift+Tab; activate controls with Enter/Space. Check visible focus and readable errors, including a missing-key connection check.</li><li>Pause a demo task, refresh and reconnect. Verify chat, saved drafts, task progress and campaign outcomes return. Mode intentionally resets to labeled Demo.</li></ol><p>Report any failed step and the viewport/input method used. No visual pass is inferred from a build or configuration.</p></section></>;
}
